# ============== CLINICAL THRESHOLDS (Based on CDC/WHO/ACOG Guidelines) ==============

# Blood Pressure Categories (ACC/AHA)
BP_NORMAL_SYSTOLIC = 120
BP_ELEVATED_SYSTOLIC = 130
BP_HIGH_STAGE1_SYSTOLIC = 140
BP_HIGH_STAGE2_SYSTOLIC = 160
BP_CRISIS_SYSTOLIC = 180

BP_NORMAL_DIASTOLIC = 80
BP_HIGH_STAGE1_DIASTOLIC = 90
BP_HIGH_STAGE2_DIASTOLIC = 100
BP_CRISIS_DIASTOLIC = 120

# Blood Sugar (mg/dL)
SUGAR_NORMAL_MAX = 100
SUGAR_PREDIABETES_MAX = 125
SUGAR_DIABETES_MIN = 126
SUGAR_DANGEROUS_MIN = 250

# Sleep Hours
SLEEP_MIN_HEALTHY = 7
SLEEP_MAX_HEALTHY = 9

# BMI Categories
BMI_UNDERWEIGHT = 18.5
BMI_NORMAL_MAX = 24.9
BMI_OVERWEIGHT_MAX = 29.9
BMI_OBESE_MIN = 30

# Pregnancy-Specific (ACOG Guidelines)
PREGNANCY_HIGH_RISK_AGE_MIN = 35
PREGNANCY_HIGH_RISK_AGE_MAX = 40
PREGNANCY_PRETERM_WEEKS = 37
PREGNANCY_POSTTERM_WEEKS = 42
PREGNANCY_PREECLAMPSIA_BP_SYSTOLIC = 140
PREGNANCY_PREECLAMPSIA_BP_DIASTOLIC = 90
PREGNANCY_GESTATIONAL_DIABETES_SUGAR = 140

# Stress Level Scores
STRESS_SCORE_MAP = {
    "Low": 1,
    "Medium": 2,
    "High": 3
}